### ISSUE TITLE
Problem: upgrade to cc 1.0.63 fails to build C dependencies

### ISSUE THREAD

**Issue by tomtau** [crypto-com/thaler#2337]
https://github.com/crypto-com/thaler/runs/1421647625#step:6:1005

**Comment by trevor-crypto** [comment]
I ran into an issue like this when using `clang` instead of `gcc`.

**Comment by tomtau** [comment]
upgrade to 1.0.66 works: https://github.com/crypto-com/thaler/pull/2364
