### ISSUE TITLE
Problem: rcgen upgrade to 0.8.7 fails integration tests

### ISSUE THREAD

**Issue by tomtau** [crypto-com/thaler#2359]
```

thread 'main' panicked at 'distribution validation error: KeyPackageDecodeError', chain-abci/src/app/app_init.rs:231:17
--
168

```

**Comment by trevor-crypto** [comment]
I'm also experiencing this with the usage of `ra-enclave`. I think I've isolated it to a `yasna` issue: `Can't express a non-zero nanosecond in UTCTime`, when supplying `certificate_params.not_before` and `certificate_params.not_after`.

Going to have a deeper look today.

**Comment by trevor-crypto** [comment]
I logged this issue. We can get around it by stripping the nanoseconds ourselves, or try to get a fix for their branch.
https://github.com/est31/rcgen/issues/44

**Comment by trevor-crypto** [comment]
https://github.com/est31/rcgen/pull/45

**Comment by tomtau** [comment]
great, thanks for investigating this!

**Comment by tomtau** [comment]
https://github.com/crypto-com/thaler/pull/2366
