### ISSUE TITLE
Problem: upgrade to webpki 0.21.4 fails to compile

### ISSUE THREAD

**Issue by tomtau** [crypto-com/thaler#2361]
Possibly due to the custom ring fork for sgx
```
error[E0425]: cannot find function `fill_impl` in this scope
225	   --> /drone/src/drone/cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.16.19/src/rand.rs:160:9
226	    |
227	160 |         fill_impl(dest)
228	    |         ^^^^^^^^^ help: try: `self.fill_impl`
229	
230	   Compiling thread-pool v0.1.1
231	error: aborting due to previous error
232	
233	For more information about this error, try `rustc --explain E0425`.
234	error: could not compile `ring`.
```

**Comment by trevor-crypto** [comment]
I made a [branch](https://github.com/trevor-crypto/ring/tree/upstream-0.16.19) rebasing from `ring` upstream and `crypto-com/ring`. I also applied the changes from https://github.com/crypto-com/ring/pull/5/ to get the tests to pass when the target is sgx.

Not really sure how risky it is to move on from `ring 0.16.15`, but I figured it might continue to cause issues.

**Comment by trevor-crypto** [comment]
https://github.com/crypto-com/ring/pull/6 brings `crypto-com/ring` up to `0.16.19`
